/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";
import { createServerRootRoute } from "@tanstack/react-start/server";

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ShellRouteImport } from "./routes/shell";
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route";
import { Route as authRouteRouteImport } from "./routes/(auth)/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as authOldLoginRouteImport } from "./routes/(auth)/old-login";
import { Route as authLoginRouteImport } from "./routes/(auth)/login";
import { ServerRoute as ApiAuthSplatServerRouteImport } from "./routes/api/auth/$";

const EditorIndexLazyRouteImport = createFileRoute("/editor/")();
const rootServerRouteImport = createServerRootRoute();

const ShellRoute = ShellRouteImport.update({
  id: "/shell",
  path: "/shell",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const authRouteRoute = authRouteRouteImport.update({
  id: "/(auth)",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const EditorIndexLazyRoute = EditorIndexLazyRouteImport.update({
  id: "/editor/",
  path: "/editor/",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/editor/index.lazy").then((d) => d.Route));
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const authOldLoginRoute = authOldLoginRouteImport.update({
  id: "/old-login",
  path: "/old-login",
  getParentRoute: () => authRouteRoute,
} as any);
const authLoginRoute = authLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => authRouteRoute,
} as any);
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootServerRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof authRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/shell": typeof ShellRoute;
  "/login": typeof authLoginRoute;
  "/old-login": typeof authOldLoginRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/editor": typeof EditorIndexLazyRoute;
}
export interface FileRoutesByTo {
  "/": typeof authRouteRouteWithChildren;
  "/shell": typeof ShellRoute;
  "/login": typeof authLoginRoute;
  "/old-login": typeof authOldLoginRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/editor": typeof EditorIndexLazyRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/(auth)": typeof authRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/shell": typeof ShellRoute;
  "/(auth)/login": typeof authLoginRoute;
  "/(auth)/old-login": typeof authOldLoginRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/editor/": typeof EditorIndexLazyRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/shell"
    | "/login"
    | "/old-login"
    | "/dashboard/"
    | "/editor";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/shell" | "/login" | "/old-login" | "/dashboard" | "/editor";
  id:
    | "__root__"
    | "/"
    | "/(auth)"
    | "/dashboard"
    | "/shell"
    | "/(auth)/login"
    | "/(auth)/old-login"
    | "/dashboard/"
    | "/editor/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  authRouteRoute: typeof authRouteRouteWithChildren;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  ShellRoute: typeof ShellRoute;
  EditorIndexLazyRoute: typeof EditorIndexLazyRoute;
}
export interface FileServerRoutesByFullPath {
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
}
export interface FileServerRoutesByTo {
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport;
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath;
  fullPaths: "/api/auth/$";
  fileServerRoutesByTo: FileServerRoutesByTo;
  to: "/api/auth/$";
  id: "__root__" | "/api/auth/$";
  fileServerRoutesById: FileServerRoutesById;
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/shell": {
      id: "/shell";
      path: "/shell";
      fullPath: "/shell";
      preLoaderRoute: typeof ShellRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)": {
      id: "/(auth)";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof authRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/editor/": {
      id: "/editor/";
      path: "/editor";
      fullPath: "/editor";
      preLoaderRoute: typeof EditorIndexLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/(auth)/old-login": {
      id: "/(auth)/old-login";
      path: "/old-login";
      fullPath: "/old-login";
      preLoaderRoute: typeof authOldLoginRouteImport;
      parentRoute: typeof authRouteRoute;
    };
    "/(auth)/login": {
      id: "/(auth)/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof authLoginRouteImport;
      parentRoute: typeof authRouteRoute;
    };
  }
}
declare module "@tanstack/react-start/server" {
  interface ServerFileRoutesByPath {
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute;
  authOldLoginRoute: typeof authOldLoginRoute;
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authOldLoginRoute: authOldLoginRoute,
};

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
);

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ShellRoute: ShellRoute,
  EditorIndexLazyRoute: EditorIndexLazyRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
};
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>();
